name: ci

on:
  push:
    branches:
      - main

jobs:
  BuildnDocker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare
        id: prep
        shell: bash
        run: |
          IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}
          echo ::set-output name=IMAGE::$IMAGE

      - name: Login to GitHub Container Repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: matteomalucchi
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.prep.outputs.IMAGE }}
          tags: |
            type=ref,event=branch
          flavor: |
            latest=true

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
